/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedBibliotecaRouteImport } from './routes/_authenticated/biblioteca'
import { Route as AuthenticatedComunidadRouteImport } from './routes/_authenticated/comunidad'
import { Route as AuthenticatedHistorialRouteImport } from './routes/_authenticated/historial'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedProgresoRouteImport } from './routes/_authenticated/progreso'
import { Route as AuthenticatedSesionRouteImport } from './routes/_authenticated/sesion'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBibliotecaRoute = AuthenticatedBibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComunidadRoute = AuthenticatedComunidadRouteImport.update({
  id: '/comunidad',
  path: '/comunidad',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistorialRoute = AuthenticatedHistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgresoRoute = AuthenticatedProgresoRouteImport.update({
  id: '/progreso',
  path: '/progreso',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSesionRoute = AuthenticatedSesionRouteImport.update({
  id: '/sesion',
  path: '/sesion',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/comunidad': typeof AuthenticatedComunidadRoute
  '/historial': typeof AuthenticatedHistorialRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/progreso': typeof AuthenticatedProgresoRoute
  '/sesion': typeof AuthenticatedSesionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/comunidad': typeof AuthenticatedComunidadRoute
  '/historial': typeof AuthenticatedHistorialRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/progreso': typeof AuthenticatedProgresoRoute
  '/sesion': typeof AuthenticatedSesionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/_authenticated/comunidad': typeof AuthenticatedComunidadRoute
  '/_authenticated/historial': typeof AuthenticatedHistorialRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/progreso': typeof AuthenticatedProgresoRoute
  '/_authenticated/sesion': typeof AuthenticatedSesionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/biblioteca'
    | '/comunidad'
    | '/historial'
    | '/inicio'
    | '/perfil'
    | '/progreso'
    | '/sesion'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/biblioteca'
    | '/comunidad'
    | '/historial'
    | '/inicio'
    | '/perfil'
    | '/progreso'
    | '/sesion'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/biblioteca'
    | '/_authenticated/comunidad'
    | '/_authenticated/historial'
    | '/_authenticated/inicio'
    | '/_authenticated/perfil'
    | '/_authenticated/progreso'
    | '/_authenticated/sesion'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/biblioteca': {
      id: '/_authenticated/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof AuthenticatedBibliotecaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comunidad': {
      id: '/_authenticated/comunidad'
      path: '/comunidad'
      fullPath: '/comunidad'
      preLoaderRoute: typeof AuthenticatedComunidadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historial': {
      id: '/_authenticated/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof AuthenticatedHistorialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progreso': {
      id: '/_authenticated/progreso'
      path: '/progreso'
      fullPath: '/progreso'
      preLoaderRoute: typeof AuthenticatedProgresoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sesion': {
      id: '/_authenticated/sesion'
      path: '/sesion'
      fullPath: '/sesion'
      preLoaderRoute: typeof AuthenticatedSesionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBibliotecaRoute: typeof AuthenticatedBibliotecaRoute
  AuthenticatedComunidadRoute: typeof AuthenticatedComunidadRoute
  AuthenticatedHistorialRoute: typeof AuthenticatedHistorialRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedProgresoRoute: typeof AuthenticatedProgresoRoute
  AuthenticatedSesionRoute: typeof AuthenticatedSesionRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBibliotecaRoute: AuthenticatedBibliotecaRoute,
  AuthenticatedComunidadRoute: AuthenticatedComunidadRoute,
  AuthenticatedHistorialRoute: AuthenticatedHistorialRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedProgresoRoute: AuthenticatedProgresoRoute,
  AuthenticatedSesionRoute: AuthenticatedSesionRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
