/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedBibliotecaRouteImport } from './routes/_authenticated/biblioteca'
import { Route as AuthenticatedComunidadRouteImport } from './routes/_authenticated/comunidad'
import { Route as AuthenticatedCrearTemaRouteImport } from './routes/_authenticated/crear-tema'
import { Route as AuthenticatedGrafoRouteImport } from './routes/_authenticated/grafo'
import { Route as AuthenticatedHistorialRouteImport } from './routes/_authenticated/historial'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedProgresoRouteImport } from './routes/_authenticated/progreso'
import { Route as AuthenticatedSesionRouteImport } from './routes/_authenticated/sesion'
import { Route as EIdRouteImport } from './routes/e.$id'
import { Route as AuthenticatedTemaIdRouteImport } from './routes/_authenticated/tema.$id'
import { Route as AuthenticatedUIdRouteImport } from './routes/_authenticated/u.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBibliotecaRoute = AuthenticatedBibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComunidadRoute = AuthenticatedComunidadRouteImport.update({
  id: '/comunidad',
  path: '/comunidad',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrearTemaRoute = AuthenticatedCrearTemaRouteImport.update({
  id: '/crear-tema',
  path: '/crear-tema',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGrafoRoute = AuthenticatedGrafoRouteImport.update({
  id: '/grafo',
  path: '/grafo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistorialRoute = AuthenticatedHistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgresoRoute = AuthenticatedProgresoRouteImport.update({
  id: '/progreso',
  path: '/progreso',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSesionRoute = AuthenticatedSesionRouteImport.update({
  id: '/sesion',
  path: '/sesion',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const EIdRoute = EIdRouteImport.update({
  id: '/e/$id',
  path: '/e/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTemaIdRoute = AuthenticatedTemaIdRouteImport.update({
  id: '/tema/$id',
  path: '/tema/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUIdRoute = AuthenticatedUIdRouteImport.update({
  id: '/u/$id',
  path: '/u/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/comunidad': typeof AuthenticatedComunidadRoute
  '/crear-tema': typeof AuthenticatedCrearTemaRoute
  '/grafo': typeof AuthenticatedGrafoRoute
  '/historial': typeof AuthenticatedHistorialRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/progreso': typeof AuthenticatedProgresoRoute
  '/sesion': typeof AuthenticatedSesionRoute
  '/e/$id': typeof EIdRoute
  '/tema/$id': typeof AuthenticatedTemaIdRoute
  '/u/$id': typeof AuthenticatedUIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/comunidad': typeof AuthenticatedComunidadRoute
  '/crear-tema': typeof AuthenticatedCrearTemaRoute
  '/grafo': typeof AuthenticatedGrafoRoute
  '/historial': typeof AuthenticatedHistorialRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/progreso': typeof AuthenticatedProgresoRoute
  '/sesion': typeof AuthenticatedSesionRoute
  '/e/$id': typeof EIdRoute
  '/tema/$id': typeof AuthenticatedTemaIdRoute
  '/u/$id': typeof AuthenticatedUIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/_authenticated/comunidad': typeof AuthenticatedComunidadRoute
  '/_authenticated/crear-tema': typeof AuthenticatedCrearTemaRoute
  '/_authenticated/grafo': typeof AuthenticatedGrafoRoute
  '/_authenticated/historial': typeof AuthenticatedHistorialRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/progreso': typeof AuthenticatedProgresoRoute
  '/_authenticated/sesion': typeof AuthenticatedSesionRoute
  '/e/$id': typeof EIdRoute
  '/_authenticated/tema/$id': typeof AuthenticatedTemaIdRoute
  '/_authenticated/u/$id': typeof AuthenticatedUIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/biblioteca'
    | '/comunidad'
    | '/crear-tema'
    | '/grafo'
    | '/historial'
    | '/inicio'
    | '/perfil'
    | '/progreso'
    | '/sesion'
    | '/e/$id'
    | '/tema/$id'
    | '/u/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/biblioteca'
    | '/comunidad'
    | '/crear-tema'
    | '/grafo'
    | '/historial'
    | '/inicio'
    | '/perfil'
    | '/progreso'
    | '/sesion'
    | '/e/$id'
    | '/tema/$id'
    | '/u/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/biblioteca'
    | '/_authenticated/comunidad'
    | '/_authenticated/crear-tema'
    | '/_authenticated/grafo'
    | '/_authenticated/historial'
    | '/_authenticated/inicio'
    | '/_authenticated/perfil'
    | '/_authenticated/progreso'
    | '/_authenticated/sesion'
    | '/e/$id'
    | '/_authenticated/tema/$id'
    | '/_authenticated/u/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  EIdRoute: typeof EIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/biblioteca': {
      id: '/_authenticated/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof AuthenticatedBibliotecaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comunidad': {
      id: '/_authenticated/comunidad'
      path: '/comunidad'
      fullPath: '/comunidad'
      preLoaderRoute: typeof AuthenticatedComunidadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crear-tema': {
      id: '/_authenticated/crear-tema'
      path: '/crear-tema'
      fullPath: '/crear-tema'
      preLoaderRoute: typeof AuthenticatedCrearTemaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/grafo': {
      id: '/_authenticated/grafo'
      path: '/grafo'
      fullPath: '/grafo'
      preLoaderRoute: typeof AuthenticatedGrafoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historial': {
      id: '/_authenticated/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof AuthenticatedHistorialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progreso': {
      id: '/_authenticated/progreso'
      path: '/progreso'
      fullPath: '/progreso'
      preLoaderRoute: typeof AuthenticatedProgresoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sesion': {
      id: '/_authenticated/sesion'
      path: '/sesion'
      fullPath: '/sesion'
      preLoaderRoute: typeof AuthenticatedSesionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/e/$id': {
      id: '/e/$id'
      path: '/e/$id'
      fullPath: '/e/$id'
      preLoaderRoute: typeof EIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tema/$id': {
      id: '/_authenticated/tema/$id'
      path: '/tema/$id'
      fullPath: '/tema/$id'
      preLoaderRoute: typeof AuthenticatedTemaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/u/$id': {
      id: '/_authenticated/u/$id'
      path: '/u/$id'
      fullPath: '/u/$id'
      preLoaderRoute: typeof AuthenticatedUIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBibliotecaRoute: typeof AuthenticatedBibliotecaRoute
  AuthenticatedComunidadRoute: typeof AuthenticatedComunidadRoute
  AuthenticatedCrearTemaRoute: typeof AuthenticatedCrearTemaRoute
  AuthenticatedGrafoRoute: typeof AuthenticatedGrafoRoute
  AuthenticatedHistorialRoute: typeof AuthenticatedHistorialRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedProgresoRoute: typeof AuthenticatedProgresoRoute
  AuthenticatedSesionRoute: typeof AuthenticatedSesionRoute
  AuthenticatedTemaIdRoute: typeof AuthenticatedTemaIdRoute
  AuthenticatedUIdRoute: typeof AuthenticatedUIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBibliotecaRoute: AuthenticatedBibliotecaRoute,
  AuthenticatedComunidadRoute: AuthenticatedComunidadRoute,
  AuthenticatedCrearTemaRoute: AuthenticatedCrearTemaRoute,
  AuthenticatedGrafoRoute: AuthenticatedGrafoRoute,
  AuthenticatedHistorialRoute: AuthenticatedHistorialRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedProgresoRoute: AuthenticatedProgresoRoute,
  AuthenticatedSesionRoute: AuthenticatedSesionRoute,
  AuthenticatedTemaIdRoute: AuthenticatedTemaIdRoute,
  AuthenticatedUIdRoute: AuthenticatedUIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  EIdRoute: EIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
