INSERT INTO public.study_sessions (user_id, topic_id, duration_minutes, explanation_text, is_public, started_at, created_at)
SELECT '835d0275-253b-4845-82af-41753c9d2577', t.id, v.dur, v.txt, v.pub, now() - (v.dias || ' days')::interval, now() - (v.dias || ' days')::interval
FROM (VALUES
 ('Derivadas', 30, 'La derivada mide cómo cambia una función en un punto: es la pendiente de la recta tangente. Se calcula como el límite del cociente incremental cuando h tiende a cero. Sirve para encontrar máximos y mínimos, velocidades y tasas de cambio. Reglas clave: potencia, producto, cociente y cadena.', true, 12),
 ('Teorema de Pitágoras', 15, 'En todo triángulo rectángulo, el cuadrado de la hipotenusa es igual a la suma de los cuadrados de los catetos: a² + b² = c². Se usa para calcular distancias, en construcción y en geometría analítica. Ejemplo: catetos 3 y 4 dan hipotenusa 5.', true, 11),
 ('Leyes de Newton', 30, 'Primera ley (inercia): un cuerpo mantiene su estado de reposo o movimiento si no actúa una fuerza neta. Segunda: la fuerza es igual a masa por aceleración (F = m·a). Tercera: a toda acción le corresponde una reacción igual y opuesta. Explican desde una pelota que rueda hasta el lanzamiento de cohetes.', true, 10),
 ('Tabla periódica', 15, 'La tabla periódica ordena los elementos químicos por número atómico. Las filas son periodos y las columnas, grupos con propiedades parecidas: metales alcalinos, halógenos, gases nobles. Mendeléyev la propuso en 1869 y hasta predijo elementos que todavía no se conocían.', false, 9),
 ('Fotosíntesis', 15, 'Las plantas usan la luz del sol, el agua y el dióxido de carbono para fabricar glucosa y liberar oxígeno. Ocurre en los cloroplastos gracias a la clorofila. Tiene una fase luminosa, que produce energía, y una fase oscura (ciclo de Calvin), que fija el carbono. Es la base de casi todas las cadenas alimentarias.', true, 8),
 ('ADN y genética', 30, 'El ADN es una doble hélice formada por nucleótidos con cuatro bases: adenina, timina, citosina y guanina. Guarda la información genética en genes que se traducen en proteínas. Mendel descubrió las leyes de la herencia con arvejas; hoy sabemos que los genes vienen en pares, uno de cada progenitor.', true, 7),
 ('La Revolución Francesa', 30, 'Entre 1789 y 1799 Francia pasó de la monarquía absoluta a la república. Las causas fueron la crisis económica, la desigualdad entre estamentos y las ideas de la Ilustración. La toma de la Bastilla, la Declaración de los Derechos del Hombre y el Terror marcan sus etapas. Termina con el ascenso de Napoleón.', true, 6),
 ('Revolución de Mayo', 15, 'En mayo de 1810, en Buenos Aires, un cabildo abierto destituyó al virrey Cisneros y formó la Primera Junta. Fue posible por la crisis de la monarquía española tras la invasión napoleónica. Es el inicio del proceso de independencia argentina, que se declara en 1816.', false, 5),
 ('Calentamiento global', 15, 'El aumento de gases de efecto invernadero, sobre todo dióxido de carbono por quemar combustibles fósiles, retiene más calor en la atmósfera. Consecuencias: deshielo, subida del nivel del mar y eventos climáticos extremos. Las soluciones pasan por energías renovables, eficiencia y conservación de bosques.', true, 4),
 ('Economía de mercado', 15, 'En una economía de mercado los precios se forman por la oferta y la demanda. Si hay mucha demanda y poca oferta, el precio sube; si sobra oferta, baja. El Estado puede intervenir con impuestos, regulaciones o subsidios para corregir fallas como los monopolios.', true, 3),
 ('Variables y funciones en programación', 30, 'Una variable es un nombre que guarda un valor que puede cambiar, como edad = 20. Una función es un bloque de código reutilizable que recibe parámetros y devuelve un resultado. Por ejemplo, una función sumar(a, b) devuelve a + b. Permiten organizar el programa y no repetir código.', true, 2),
 ('Martin Fierro', 30, 'El Martín Fierro de José Hernández (1872) cuenta la vida de un gaucho perseguido y obligado a ir a la frontera. Escrito en verso y con el habla rural, denuncia la injusticia contra los gauchos. Es la obra cumbre de la literatura gauchesca y un símbolo de la identidad argentina.', true, 1)
) AS v(titulo, dur, txt, pub, dias)
JOIN public.topics t ON t.title = v.titulo;